{% set name = "tethys-platform" %}
{% set version = "4.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tethysplatform/tethys/archive/refs/tags/{{ version }}.tar.gz
  sha256: f729907dc159da9949849f798f97b00b36f2ee9fa30d83b469568e8e3f9d1510

build:
  noarch: python
  number: 0
  entry_points:
    - tethys = tethys_cli:tethys_command

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
    - pbr
  run:
    - python
    - pycrypto
    - pyopenssl
    - docker-py
    - distro
    - postgresql
    - psycopg2
    - sqlalchemy
    - geoalchemy2
    - plotly
    - bokeh
    - tethys_dataset_services>=2.0.0
    - hs_restclient
    - owslib
    - requests
    - dask
    - tethys_dask_scheduler>=1.0.2
    - service_identity
    - condorpy
    - siphon
    - python-jose
    - pyjwt<2.0.0
    - arrow
    - isodate
    - django=3.2.*
    - channels=3.*
    - daphne=3.*
    - django-analytical
    - django-axes
    - django-filter
    - djangorestframework
    - django-bootstrap5
    - django-model-utils
    - django-guardian
    - django-gravatar2
    - django-mfa2
    - django-recaptcha2
    - django-simple-captcha
    - django-session-security
    - django-termsandconditions
    - social-auth-app-django
    - pillow
    - pip
    - future
    - git
    - setuptools_scm
    - openssl
    - conda

test:
  requires:
    - pip
  imports:
    - tethys_apps
    - tethys_cli
    - tethys_compute
    - tethys_config
    - tethys_gizmos
    - tethys_portal
    - tethys_quotas
    - tethys_sdk
    - tethys_services
  commands:
    - tethys version
    - tethys gen portal_config

about:
  home: http://www.tethysplatform.org/
  summary: 'A development platform for creating geospatial and scientific web applications.'
  description: |
    Tethys Platform has been designed to lower the barrier to geospatial and 
    scientific web app development. Use it to deliver your models and data as 
    interactive web apps.
  license: BSD-2-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - tethys_portal/static/tethys_portal/vendor/bootstrap-social/LICENSE
    - tethys_gizmos/static/tethys_gizmos/vendor/select2_3.5.1/LICENSE
    - tethys_gizmos/static/tethys_gizmos/vendor/dagre-d3/LICENSE
    - tethys_gizmos/static/tethys_gizmos/vendor/graphlib/LICENSE
    - tethys_gizmos/static/tethys_gizmos/vendor/farbtastic/LICENSE.txt
    - tethys_gizmos/static/tethys_gizmos/vendor/lodash/LICENSE
    - tethys_gizmos/static/tethys_gizmos/vendor/dagre/LICENSE
    - tethys_gizmos/static/tethys_gizmos/vendor/bootstrap_switch/LICENSE
  doc_url: http://docs.tethysplatform.org/en/stable/
  dev_url: https://github.com/tethysplatform/tethys

extra:
  recipe-maintainers:
    - swainn
    - sdc50
